### ISSUE TITLE
[Bug]: The results of the selefra run do not match the results in the database

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra#113]
### selefra version

pre

### Does it still exist

Yes

### bug description

1. Using `selefra apply` you can see that 1 result is output
<img width="856" alt="image" src="https://user-images.githubusercontent.com/124039940/221472783-1d6cda23-ca3b-49fb-b9d2-13365873e60c.png">

2. But putting this SQL into the database and executing it has 2 results
<img width="688" alt="image" src="https://user-images.githubusercontent.com/124039940/221472900-832aecf2-cc58-4dd5-8001-a00ea835ebd2.png">

My configuration file is as follows.
```yaml
selefra:
    name: slack
    cli_version: v0.0.8
    providers:
      - name: slack
        source: slack
        version: "=0.0.2"
rules:
  - name: public_files_exist
    query: |
      SELECT
        *
      FROM
        slack_file
      WHERE
        public_url_shared;
    output: "Public files exist, file name: {{.name}}, permalink public: {{.permalink_public}}"
```
