### ISSUE TITLE
[Feat] Suggested simplification of init-generated content

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra#135]
### selefra version

pre

### Does it still exist

Yes

### bug description

I found that currently when executing `selefra init`, it generates a lot of stuff, which is causing me some trouble.

Because some of the information generated is useless to me, it is recommended to generate only the necessary information, and not the non-essential information.

For example, it is sufficient to generate only the following part of the content.

```yaml
selefra:
    name: selefra-demo
    cloud:
        project: selefra-demo
    cli_version: latest
    log_level: info
    providers:
        - name: aws
          source: aws
          version: latest
rules:
  - name: example_rule
    query: |
      SELECT 
        *
      FROM 
        aws_ec2_ebs_volumes 
      WHERE 
        encrypted = FALSE;
    output: 'EBS volume are unencrypted, EBS id: {{.id}}'
```
