### ISSUE TITLE
[Bug]: Specifying Selefra Registry is not supported

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra#197]
### Version

0.0.12

### What happened?

Specifying Selefra Registry is not supported, Here are the contents of my configuration file.

```yaml
selefra:
  name: aws-misconfigure-s3
  cli_version: ">=0.0.9,<=0.0.11"
  providers:
    - name: aws
      source: aws
      version: ">=0.0.9,<=0.0.14"
modules:
  - name: aws-misconfigure-s3
    uses: selefra/rules-aws-misconfigure-s3
```

When I run `selefra apply` I have the following output:

```bash
❯ selefra apply
load module ./ @ /Users/**/Desktop/1 success
error[E827890]: invalid module uses source selefra/rules-aws-misconfigure-s3, unsupported module loader
 -->  /Users/**/Desktop/1/selefra.yaml:10:11 ( modules[0].uses[0] )
| 5      - name: aws
| 6        source: aws
| 7        version: ">=0.0.9,<=0.0.14"
| 8  modules:
| 9    - name: aws-misconfigure-s3
| 10     uses: selefra/rules-aws-misconfigure-s3
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
--> See our docs: http://selefra.io/docs

local directory module loader load  ./ failed.
Apply done
```
