### ISSUE TITLE
[Feature]: Discussion of support for private registry

### ISSUE THREAD

**Issue by monserrat101** [selefra/selefra#97]
### Related

no

### Feature

support for private registry for modules and providers 

### Alternatives

I already have a general idea. It is still based on github to do registry, but users need to configure related repo full name and auth token in selefra block

### Reference

New add configuration block: 

```yaml
selefra:
  registry:
    # Indicates that a github based registry is used
    type: github
    # The fullname of the registry repo
    repo: private-org/private-repo
    # Access to github's credentials, may be api token
    token: xxxx
    # "modules" or "providers", If not, the default is to use the registry for both
    scope: modules
```
